// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.github.rr250.mattermost.plugin.reply.private",
  "name": "Private Reply Command",
  "description": "This plugin allows us to reply privately.",
  "homepage_url": "https://github.com/rr250/mattermost_plugin_reply_private/",
  "support_url": "https://github.com/rr250/mattermost_plugin_reply_private",
  "icon_path": "",
  "version": "1.0.0",
  "min_server_version": "5.14.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": "server/dist/plugin-freebsd-amd64"
  },,
  "settings_schema": {
    "header": "",
    "footer": "",
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
